# Numpy 

#            
            NumPy - Numerical Python
            perform a wide variety of mathematical operations on arrays
            library of high-level mathematical functions that operate on the arrays and matrices.
            elements in a NumPy array have to be of the same data type,commonly numeric (float or integer).
            NumPy arrays are more compact than lists, i.e. they take much lesser storage space than lists

# Installing NumPy :
            pip install numpy

# Importing NumPy :

In [2]:
 import numpy as np

In [3]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
print(a[0]) #indexing starts with 0 and it is row wise

[1 2 3 4]


In [6]:
print(a[0][3])

4


In [7]:
print(a[2]) 

[ 9 10 11 12]


In [ ]:
a[1][1]

In [8]:
#To get the shape of the array
a.shape

(3, 4)

In [9]:
b.shape #for a 1D array only the number of columns are specified

(3,)

In [10]:
#To get the data type of the array
b.dtype

dtype('int32')

In [11]:
print(type(a))

<class 'numpy.ndarray'>


In [12]:
#Gives the dimesion of the array.
a.ndim

2

In [13]:
#Computational speed 

l1 = range(10000)
l2 = [i**2 for i in range(10000)]

In [14]:
%timeit list(map(lambda x, y: x*y, l1, l2))

1.51 ms ± 33.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [15]:
a1 = np.array(l1)
b1 = np.array(l2)

In [16]:
%timeit a1*b1

14.6 µs ± 483 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [17]:
#arrange function arranges the numbers with the given limit.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#Specifing the start and stop and intervals
np.arange(1, 15, 3)

array([ 1,  4,  7, 10, 13])

In [19]:
#specifing the datatype
np.arange(1, 10, 3, dtype=float)

array([1., 4., 7.])

In [20]:
np.arange(2, 6)

array([2, 3, 4, 5])

In [21]:
np.arange(-8, -1)

array([-8, -7, -6, -5, -4, -3, -2])

In [22]:
#Zeros
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
#create a matrix with ones
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
#create a  identy matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.full((3,3),2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [26]:
np.full((3,3),2.2, dtype= np.float)

C:\Users\Suba\AppData\Local\Temp\ipykernel_13960\1412458525.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.full((3,3),2.2, dtype= np.float)


array([[2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2]])

In [115]:
np.full((3,3),2.2, dtype= np.int)

C:\Users\Suba\AppData\Local\Temp\ipykernel_13960\559008274.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.full((3,3),2.2, dtype= np.int)


array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [28]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [29]:
# between 0 and 1
np.random.random()

0.5958551052806017

In [30]:
np.random.random([3,3])

array([[0.91545372, 0.40961126, 0.38040422],
       [0.76916467, 0.24333123, 0.70815025],
       [0.69895527, 0.50048941, 0.4391962 ]])

In [116]:
# 100 values between 1 and 50
a = np.linspace(50,100,100)
a

array([ 50.        ,  50.50505051,  51.01010101,  51.51515152,
        52.02020202,  52.52525253,  53.03030303,  53.53535354,
        54.04040404,  54.54545455,  55.05050505,  55.55555556,
        56.06060606,  56.56565657,  57.07070707,  57.57575758,
        58.08080808,  58.58585859,  59.09090909,  59.5959596 ,
        60.1010101 ,  60.60606061,  61.11111111,  61.61616162,
        62.12121212,  62.62626263,  63.13131313,  63.63636364,
        64.14141414,  64.64646465,  65.15151515,  65.65656566,
        66.16161616,  66.66666667,  67.17171717,  67.67676768,
        68.18181818,  68.68686869,  69.19191919,  69.6969697 ,
        70.2020202 ,  70.70707071,  71.21212121,  71.71717172,
        72.22222222,  72.72727273,  73.23232323,  73.73737374,
        74.24242424,  74.74747475,  75.25252525,  75.75757576,
        76.26262626,  76.76767677,  77.27272727,  77.77777778,
        78.28282828,  78.78787879,  79.29292929,  79.7979798 ,
        80.3030303 ,  80.80808081,  81.31313131,  81.81

In [33]:
#memory used by each array element in bytes
a.itemsize

8

In [34]:
np.arange(18).reshape(2,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

# accessing Numpy array element

In [36]:
a = np.array([2,4,6,8,10,12,14,16])
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
a[2]

In [38]:
a[[2,4,6]]

array([ 6, 10, 14])

In [ ]:
a[2:]

In [41]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[2,2] #Guess

In [43]:
a > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [44]:
a[a > 2]

array([3, 4, 5, 6, 7, 8, 9])

In [59]:
a = np.arange(10)
print("values in a is",a)
b = a
b[0] = 11

values in a is [0 1 2 3 4 5 6 7 8 9]


In [50]:
#What will be the value of a
a

In [ ]:
np.shares_memory(a,b)

In [ ]:
#What will happen here?
a = np.arange(10)
print("values in a is",a)
b = a.copy()

In [61]:
b[0] = 11

In [ ]:
print('values of a is',a)
print('values of b is',b)

In [ ]:
np.shares_memory(a,b)

# Operations

In [64]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
#Transpose
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
b= np.array([[7,8,9],[10,11,12]])
b


array([[ 7,  8,  9],
       [10, 11, 12]])

In [68]:
a == b

array([[False, False, False],
       [False, False, False]])

In [70]:
#Vertical stacking
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [72]:
#Horizontal stacking

np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [73]:
#Mathmatical operation

In [75]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [77]:
# Try 
np.exp(a)
a.std()
np.median(a)
np.sum(a)

45

In [84]:
#Adding,sorting

In [85]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [86]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [87]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [88]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [99]:
data = np.array([[1, 2], [3, 4]])
print(data)
ones = np.array([[1, 1], [1, 1]])
print(ones)


[[1 2]
 [3 4]]
[[1 1]
 [1 1]]


In [100]:
data + ones

array([[2, 3],
       [4, 5]])

In [107]:
data = np.array([[1, 2], [3, 4]])
print(data)
ones = np.array([[1, 1], [1, 1]])
print(ones)
data * ones

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]


array([[1, 2],
       [3, 4]])

In [108]:
[[1*1, 2*1],
 [3*1, 4*1]]

[[1, 2], [3, 4]]

In [ ]:
# Link
#https://numpy.org/doc/stable/user/absolute_beginners.html

In [114]:
#Linear Algebra packages

In [110]:
a = np.diag([2, 4, 6])
det = np.linalg.det(a) #finds the determinent of a
det

47.999999999999986

In [111]:
np.linalg.inv(a) #find the inverse of a

array([[0.5       , 0.        , 0.        ],
       [0.        , 0.25      , 0.        ],
       [0.        , 0.        , 0.16666667]])

In [112]:
np.linalg.eig(a) #find the eigen values of a

(array([2., 4., 6.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))